apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel-k8s.configMapName" . }}
  namespace: {{ include "laravel-k8s.namespace" . }}
  labels:
    {{- include "laravel-k8s.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
