{{- if .Values.queue.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-k8s.fullname" . }}-queue
  namespace: {{ include "laravel-k8s.namespace" . }}
  labels:
    {{- include "laravel-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: queue
spec:
  replicas: {{ .Values.queue.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "laravel-k8s.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: queue
  template:
    metadata:
      labels:
        {{- include "laravel-k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: queue
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml")    . | sha256sum }}
    spec:
      serviceAccountName: {{ include "laravel-k8s.serviceAccountName" . }}
      {{- include "laravel-k8s.imagePullSecrets" . | nindent 6 }}
      terminationGracePeriodSeconds: 60   # let in-flight job finish
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: queue
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Override the supervisord CMD with the queue worker process.
          command: {{ toJson .Values.queue.command }}
          envFrom:
            {{- include "laravel-k8s.envFrom" . | nindent 12 }}
          resources:
            {{- toYaml .Values.queue.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: storage
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            - name: tmp
              mountPath: /tmp
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "laravel-k8s.pvcName" . }}
        {{- end }}
        - name: tmp
          emptyDir: {}
{{- end -}}
