apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-k8s.fullname" . }}
  namespace: {{ include "laravel-k8s.namespace" . }}
  labels:
    {{- include "laravel-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "laravel-k8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
