#!/usr/bin/env bash
#
# Provision the 5 VMs that make up the HA kubeadm cluster:
#   - cp1, cp2, cp3   (control-plane / master nodes — 3 for proper etcd quorum)
#   - w1,  w2          (worker nodes)
#
# Each VM is a small Ubuntu 22.04 image launched via multipass + qemu (KVM).
# We use 22.04 inside the VMs even though the host is 24.04 — kubeadm 1.30
# is best-tested against jammy and there's nothing 24.04-specific we need
# inside the cluster.
#
# Run on the HOST (40.81.255.50). Idempotent: re-running re-uses existing VMs.
#
# Resource budget per VM (room to spare on a D8as_v5):
#   CP:     2 vCPU, 2.5 GB RAM, 12 GB disk     × 3 = 6 vCPU, 7.5 GB
#   Worker: 2 vCPU, 2.5 GB RAM, 12 GB disk     × 2 = 4 vCPU, 5.0 GB
#   Total: 10 vCPU (slight overcommit, fine), 12.5 GB RAM, 60 GB disk.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ---- Config ----
CP_NODES=("cp1" "cp2" "cp3")
WORKER_NODES=("w1" "w2")
CP_CPUS="${CP_CPUS:-2}"
CP_MEM="${CP_MEM:-2500M}"
CP_DISK="${CP_DISK:-12G}"
W_CPUS="${W_CPUS:-2}"
W_MEM="${W_MEM:-2500M}"
W_DISK="${W_DISK:-12G}"
UBUNTU_RELEASE="${UBUNTU_RELEASE:-22.04}"
PUBKEY_FILE="${PUBKEY_FILE:-$HOME/.ssh/id_ed25519.pub}"

# ---- Make sure multipass + qemu driver are installed ----
if ! command -v multipass >/dev/null 2>&1; then
    echo "[multipass] Installing multipass via snap ..."
    sudo snap install multipass --classic
fi
sudo multipass set local.driver=qemu || true

# ---- Generate SSH key for the host -> VM access if missing ----
if [[ ! -f "${PUBKEY_FILE}" ]]; then
    echo "[ssh] Generating ${PUBKEY_FILE%.pub} for host->VM convenience ..."
    ssh-keygen -t ed25519 -N "" -f "${PUBKEY_FILE%.pub}"
fi
PUBKEY="$(cat "${PUBKEY_FILE}")"

# ---- Cloud-init payload (shared by all VMs) ----
CLOUDINIT="$(mktemp)"
cat >"${CLOUDINIT}" <<EOF
#cloud-config
package_update: true
package_upgrade: false
packages: [ curl, ca-certificates, gnupg, apt-transport-https, jq ]
ssh_authorized_keys:
  - ${PUBKEY}
runcmd:
  - swapoff -a
  - sed -ri '/\sswap\s/s/^/#/' /etc/fstab
  - hostnamectl set-hostname --static \$(hostname)
EOF

# ---- Helper: create or skip ----
launch() {
    local name="$1" cpus="$2" mem="$3" disk="$4"
    if multipass info "$name" >/dev/null 2>&1; then
        echo "[multipass] $name already exists, skipping launch."
    else
        echo "[multipass] launching $name (${cpus} vCPU, ${mem} RAM, ${disk} disk) ..."
        multipass launch "${UBUNTU_RELEASE}" \
            --name "$name" \
            --cpus "$cpus" --memory "$mem" --disk "$disk" \
            --cloud-init "${CLOUDINIT}"
    fi
}

# ---- Launch all VMs in series (multipass doesn't love parallel launches) ----
for n in "${CP_NODES[@]}"; do launch "$n" "$CP_CPUS" "$CP_MEM" "$CP_DISK"; done
for n in "${WORKER_NODES[@]}"; do launch "$n" "$W_CPUS" "$W_MEM" "$W_DISK"; done

rm -f "${CLOUDINIT}"

echo
echo "[multipass] Cluster VMs:"
multipass list

# ---- Emit a small file with discovered IPs so other scripts can source it ----
ENVFILE="${ROOT}/cluster.env"
{
    echo "# Auto-generated by 05-launch-multipass-vms.sh"
    for n in "${CP_NODES[@]}" "${WORKER_NODES[@]}"; do
        ip="$(multipass info "$n" | awk '/IPv4/{print $2; exit}')"
        printf '%s_IP=%s\n' "${n^^}" "$ip"
    done
} >"${ENVFILE}"

echo
echo "[multipass] Wrote IPs to ${ENVFILE}:"
cat "${ENVFILE}"

echo
echo "[multipass] Done. Next: bash scripts/00-prereqs-on-all.sh"
